FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY WorkingGood.Tool/WorkingGood.Tool.Domain/WorkingGood.Tool.Domain.csproj ./Domain/
COPY WorkingGood.Tool/WorkingGood.Tool.Infrastructure/WorkingGood.Tool.Infrastructure.csproj ./Infrastructure/
COPY WorkingGood.Tool/Server/WorkingGood.Tool.Server.csproj ./Server/
RUN dotnet restore ./Server/WorkingGood.Tool.Server.csproj
COPY . ./
RUN dotnet publish ./WorkingGood.Tool.sln -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "WorkingGood.Tool.Server.dll"]

ENV ASPNETCORE_ENVIRONMENT="Development"
ENV TZ="Europe/Warsaw"
EXPOSE 80
EXPOSE 443